### PR TITLE
fix: RN 0.79 build

### LINKED ISSUE #22: error building with react native 0.79
I'm seeing the error below when building for react native 0.79 with the new arch enabled:

```
.../React-RuntimeApple/React_RuntimeApple.framework/Headers/ReactCommon/RCTHost.h:12:9: fatal error: 'react/runtime/JSRuntimeFactory.h' file not found
   12 | #import <react/runtime/JSRuntimeFactory.h>
```

I'm not sure where to begin debugging, as it seems like some sort of head path configuration issue.

### PR DESCRIPTION
**Pull request by hirbod**
Bring in the new C-API runtime headers (JSRuntimeFactoryCAPI.h) via the React-jsitooling pod so that builds on React Native 0.79+ no longer fail due to the removed JSRuntimeFactory.h.

Fixes #22

### CODE REVIEW

**Comment by hirbod** [comment]
@dominicstop a new npm release is highly appreciated.
